# Site settings
title: NBSDEV
description: NBSDEVApp Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: NBSDEV
user_description: NBSDEV Website
user_title: Mobile Developer
email: tndprodev@gmail.com
twitter_username: NathanBSOff
github_username:  NBSDEVApp
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
